events { worker_connections 1024; }

http {
    # Часть каталога: балансировка Catalog-сервиса
    upstream catalog_servers {
        server catalog-1:8000; # Имя контейнера 1 и его порт
        server catalog-2:8000; # Имя контейнера 2 и его порт
    }

    server {
        listen 80;

        # Часть регистрации: Маршрутизация всех запросов /auth/ на ваш Auth-сервис
        location /auth/ {
            rewrite ^/auth/(.*)$ /$1 break;
            proxy_pass http://auth:8000; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Часть каталога: Проксирование путей /catalog/ на upstream
        location /catalog/ {
            rewrite ^/catalog/(.*)$ /$1 break;
            proxy_pass http://catalog_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}